version: '3.8'

services:
  user_service:
    build: ./backend/user_service
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - user_service

networks:
  app-network:
    driver: bridge
